<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OutputType>Exe</OutputType>
    <RootNamespace>XRUIOS.Worker.AreaManager</RootNamespace>
    <AssemblyName>XRUIOS.Worker.AreaManager</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="../../systems/AreaManager.cs" />
  </ItemGroup>

</Project>
